name: "telegram_project"
version: "1.0"
config-version: 2

profile: "telegram_project"

# Point model-paths to your custom location
model-paths: ["telegram_project/models"]

models:
  telegram_project:
    marts:
      +materialized: table
    staging:
      +materialized: view
