version: 2

models:
  - name: stg_telegram_messages
    columns:
      - name: message_id
        tests: [not_null, unique]
      - name: message_text
        tests: [not_null]

  - name: dim_channels
    columns:
      - name: channel_id
        tests: [not_null, unique]

  - name: fct_messages
    columns:
      - name: message_id
        tests: [not_null, unique]
