version: 2

sources:
  - name: raw # Logical name used in dbt (must match your SQL)
    schema: raw # The actual schema in your database (e.g., 'raw')
    tables:
      - name: telegram_messages
        description: "Telegram messages scraped from channels"
      - name: image_detections
        description: "YOLO object detection output on images"
